version: 2

workflows:
  version: 2
  test:
    jobs:
      - python3.9
      - python3.10

jobs:
  python3.9: &template
    docker:
      - image: python:3.9
    steps:
      - checkout
      - run:
          name: Install the full development requirements
          command: pip install --progress-bar off -r requirements.txt
      - run:
          name: Run flake8 check on modeling
          command: flake8 .
      - run:
          name: Run black check on modeling
          command: black --line-length 79 --check .
      - run:
          name: Build source distribution
          command: |
              pip install --progress-bar off --upgrade pip setuptools
              python setup.py sdist
              pip install dist/`ls dist/ | grep .tar.gz`
      - run:
          name: Run unit tests
          command: |
              pytest -vv tests --junitxml /tmp/testxml/report.xml
      - store_test_results:
          path: /tmp/testxml
  python3.10:
    <<: *template
    docker:
      - image: python:3.10
